# Generated by Django 3.1 on 2020-08-28 07:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200828_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'ユーザ'},
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
