# Generated by Django 3.1 on 2020-09-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200831_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30, unique=True)),
                ('relmessage', models.ManyToManyField(related_name='reltag', to='accounts.Message')),
            ],
        ),
    ]
